Feature/badge
robuust/vue-components pull request #31
Opened 2024-11-22 10:19 UTC by j-m-peters

- [ ] I updated the changelog
- [ ] I updated the docs
- [ ] I wrote tests
- [ ] I am proud of my code

2024-11-22 11:31 UTC, joostwaaijer approved these changes

2024-11-22 11:32 UTC, joostwaaijer commented on docs/.vitepress/config.js
> +          { text: 'Badge', link: '/components/badge' },
Zou de componenten op alfabetische volgorde neerzetten. Zijn ze makkelijker terug te vinden.

2024-11-22 11:52 UTC, rutgerbakker95 requested changes

2024-11-22 11:52 UTC, rutgerbakker95 commented on tests/unit/components/BadgeBase.spec.js
> +});
Improve your Unit tests, we need to test all different scenarios here

2024-11-22 11:52 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +  dot: {
I think we have to discuss with @LuckKarssen and @sandertijink about this dot. Maybe it's a nice feature, but maybe it's overkill or not needed to use this. Are we really gonna use the `dot`?

2024-11-22 11:52 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +  close: {
I think we have to discuss this feature with @LuckKarssen and @sandertijink. Is it a nice to have a closable badge? If yes, then I would recommend using `showClose` instead of `close`. If we never gonna use this feature consider removing the close feature.

2024-11-22 11:52 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +  border: {
I have my doubts about this one, in fact we can set borders in the variant itself right? Why do we want to use a seperate `border` variant?

2024-11-22 11:52 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +    validator: (value) => /^(primary|secondary|tertiary|light|dark|danger|warning|success)?$/.test(value) || value.startsWith('custom-') || 'clear',
@LuckKarssen do we need also need "soft" color variants just like the `ButtonBase`?

2024-11-22 11:52 UTC, rutgerbakker95 commented on src/tailwind/components/badge.js
> +          borderColor: theme('colors.lime.500'),
In color variants I miss the customizable logic. Like `...theme('components.badge.primary.border')`

2024-11-22 11:52 UTC, rutgerbakker95 commented on src/tailwind/components/badge.js
> +          },
Also here I miss customizable logic `...theme('components.badge.primary.close)`

2024-11-22 11:54 UTC, rutgerbakker95 commented
@j-m-peters Im your `badge.md` I miss docs about different slots we can use with examples

2024-11-22 11:54 UTC, rutgerbakker95 commented
Please consider updating `CHANGELOG.md`

2024-11-22 11:58 UTC, j-m-peters commented on src/components/Badge.vue
> +  dot: {
Baat het niet dan schaadt het niet lijkt mij toch? Het zit er nu al in en werkt naar behoren.

2024-11-22 11:58 UTC, j-m-peters commented on src/components/Badge.vue
> +  close: {
Baat het niet dan schaadt het niet lijkt mij toch? Het zit er nu al in en werkt naar behoren.

2024-11-22 12:24 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +  close: {
Ja ik snap je gedachte hoor, ook mooi dat je verschillende varianten uitwerkt. Maar "zit er nu al in" had ook voorkomen kunnen worden als je eerst even met onze designers @LuckKarssen of @sandertijink  om tafel gaat. Of dit beetje aansluit op de wensen

2024-11-22 13:55 UTC, boboldehampsink requested changes

2024-11-22 13:55 UTC, boboldehampsink commented on docs/components/badge.md
> +import { XMarkIcon } from '@heroicons/vue/24/solid';
Remove icon

2024-11-22 13:55 UTC, boboldehampsink commented on docs/components/index.md
> +- [Badge](/components/badge): A badge component designed with **Vue 3** and **Tailwind CSS**. It includes customizable color options, large variant, show dot and show a closing button.
Put in alphabetical order, so badge before buttonbase

2024-11-22 13:55 UTC, boboldehampsink commented on src/App.vue
> +    </h3>
Idem, before buttonbase

2024-11-22 13:55 UTC, boboldehampsink commented on src/components/Badge.vue
> +    validator: (value) => /^(primary|secondary|tertiary|light|dark|danger|warning|success)(-soft)?$/.test(value) || value.startsWith('custom-') || 'clear',
Kan deze validator hergebruikt worden? Heb het idee dat deze ook al exact zo in ButtonBase zat? cc @rutgerbakker95

2024-11-22 13:55 UTC, boboldehampsink commented on src/components/Badge.vue
> +
Unnecessary newline

2024-11-22 14:03 UTC, boboldehampsink approved these changes

2024-11-22 14:55 UTC, rutgerbakker95 requested changes

2024-11-22 14:55 UTC, rutgerbakker95 commented on docs/components/badge.md
> +The `Badge` component designed with **Vue 3** and **Tailwind CSS**. It includes customizable color options, large variant, show dot and show a closing button.
```suggestion
The `Badge` component designed with **Vue 3** and **Tailwind CSS**. It includes customizable `color` options and a `large` variant.
```

2024-11-22 14:55 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +    validator: (value) => /^(primary|secondary|tertiary|light|dark|danger|warning|success)(-soft)?$/.test(value) || value.startsWith('custom-') || 'clear',
@boboldehampsink ja deze kan zo te zien wel hergebruikt worden. We kunnen inderdaad overwegen die ergens globaal te configureren

2024-11-22 14:55 UTC, rutgerbakker95 commented on src/components/Badge.vue
> +  },
Consider using `size` prop instead, just like `ButtonBase`. This is more future proof if we choose to add more size variants. And it's more consistent naming method within the library.

2024-11-22 14:57 UTC, rutgerbakker95 commented
@j-m-peters also make sure you test this component in one of our projects (like NZO e-learning)

2024-11-25 13:40 UTC, boboldehampsink requested changes

2024-11-25 13:40 UTC, boboldehampsink commented on src/composables/useColorValidator.js
> + */
Missing return type in docblock

2024-11-25 13:40 UTC, boboldehampsink commented on src/components/ButtonBase.vue
> +import useColorValidator from '@/composables/useColorValidator.js';
specifying .js is not needed

2024-11-25 13:54 UTC, j-m-peters commented on src/components/ButtonBase.vue
> +import useColorValidator from '@/composables/useColorValidator.js';
Ik krijg een error dat het wel nodig is

2024-11-25 13:56 UTC, boboldehampsink commented on src/components/ButtonBase.vue
> +import useColorValidator from '@/composables/useColorValidator.js';
ok dan is die linter hier anders ingesteld

2024-11-25 13:56 UTC, rutgerbakker95 commented on src/components/ButtonBase.vue
> +import useColorValidator from '@/composables/useColorValidator.js';
Zou normaal idd niet hoeven.. zie jij hier iets geks @boboldehampsink https://github.com/robuust/vue-components/blob/develop/eslint.config.js

2024-11-25 13:57 UTC, boboldehampsink requested changes

2024-11-25 13:57 UTC, boboldehampsink commented on src/components/ButtonBase.vue
> +
Unnecessary newline

2024-11-25 13:59 UTC, merged